- name: Install web-server Apache
  hosts: web
  become: yes

  tasks:
  - name: Install Apahce web-server
    yum: name=httpd state=latest
  - name: Start Apache and Enable it on the server
    service: name=httpd state=started enabled=yes
  

- name: Install Haproxy
  hosts: lb
  become: yes
  tasks:
  - name: Download and install haproxy
    yum: name=haproxy state=present
  - name: Configure the haproxy cnf file with hosts
    template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
    notify: restart haproxy
  - name: Start the haproxy service
    service: name=haproxy state=started enabled=yes
  handlers:
  - name: restart haproxy
    service: name=haproxy state=restarted


  